name: CI
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Update theme
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.80.0"

      - name: Build
        run: hugo --minify --log --templateMetrics --templateMetricsHints -verboseLog -D
      
      - name: CNAME staging
        run: echo "pedrofelgueiras.fun" > ./public/CNAME
        if: ${{ github.ref == 'refs/heads/develop' }}

      - name: Deploy to staging
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@cp_instead_of_deleting
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'public'
          destination-github-username: 'jpfelgueiras'
          destination-repository-name: 'blog-staging'
          user-email: jpfelgueiras@gmail.com
        if: ${{ github.ref == 'refs/heads/develop' }}
      
      - name: CNAME production
        run: echo "pedrofelgueiras.com" > ./public/CNAME
        if: ${{ github.ref == 'refs/heads/main' }}

        
      - name: Deploy to production
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./public
        if: ${{ github.ref == 'refs/heads/main' }}

      - name: Purge cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        if: ${{ github.ref == 'refs/heads/main' }}
